apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: healthletic-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: healthletic-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
