# Number of pod replicas
replicaCount: 1

image:
  # Abhi local Docker image name
  # Later: change to "your-dockerhub-username/healthletics"
  repository:  xenin007/healthletics-devops
  pullPolicy: IfNotPresent
  tag: "0.1.0"

service:
  name: healthletic-app
  type: ClusterIP
  port: 8080

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5

resources: {}
